- README.md
There wasn't clear instructions on how they should be added to the list, but here is my request.
> Adds 0x1337_1337 for Mark Olsson (k0d)

- README.md
Not too sure how this is supposed to be setup but looks like i need one.
> Add id for Bruce Segal/skieast

- README.md
As part of this I would also like for a wemos-creations repo to be created similiar to espressif-creations.
Mentioned here as well.
https://discord.com/channels/327254708534116352/327298996332658690/966414092715831316
Related this this CP PR to add the Wemos C3 Board
https://github.com/adafruit/circuitpython/pull/6256
> Add Wemos Creator

- README.md
Link the Creator ID to the Creations Repo.
> add wemos creations link

- README.md
- creations/dfrobot.md
- creations/espressif.md
- creations/hardkernel.md
- creations/lilygo.md
- creations/seeed-studio.md
- creations/wemos.md
> Move community administered creation ids into this repo.

- creations/espressif.md
https://github.com/espressif/esp-who/blob/master/docs/en/get-started/ESP-EYE_Getting_Started_Guide.md
> Allocate an ID for ESP-EYE devkit from Espressif

- creations/m5stack.md
> Correct M5 Creator ID

- README.md
- creations/ai-thinker.md
This is a step of resolving https://github.com/adafruit/circuitpython/issues/6839
> Allocate unique ID for ai_thinker_esp32-c3s-2m

- README.md
- creations/espressif.md
- creations/luatos.md
All the documentation is in chinese but these boards seem to now be pretty widely sold by the usual suspects: https://wiki.luatos.com/chips/esp32c3/board.html
>  ID for Luatos Core-ESP32C3 board for use with Circuitpython

- creations/m5stack.md
Adding creation IDs for the following board:
- M5Stack Atom Matrix
- M5Stack Atom Echo
- M5Stack Atom U
> Added M5Stack Atom Matrix, Echo and U

- creations/lilygo.md
ESP32 board with ST7789 display.
https://github.com/Xinyuan-LilyGO/TTGO-T-Display
> Add Lilygo TTGO T-Display

- README.md
- creations/deneyap.md
Add Deneyap Development Board
Deneyap Kart (ESP32)
Deneyap Kart 1A (ESP32)
Deneyap Kart G (ESP32-C3)
> Add Deneyap Development Board

- creations/m5stack.md
Add creation ID from M5Stack Core2
> Add M5Stack Core2

- creations/m5stack.md
https://shop.m5stack.com/products/esp32-psram-timer-camera-x-ov3660
https://www.adafruit.com/product/4959
> m5stack timer camera x

- README.md
- creations/weact.md
Got a WeAct board from their official store, the links are in the new files.
Not in any way affiliated with them.
I am porting CircuitPython to it (PR link: https://github.com/adafruit/circuitpython/pull/8550).
> Add WeAct & one of their boards.

- README.md
- creations/oxocard.md
I am porting CircuitPython to the oxocard boards : https://github.com/adafruit/circuitpython/pull/8600
> Add Oxocard boards

- README.md
- creations/sunton.md
Added new creator (Sunton) and device (28R "Cheap Yellow Display").
> added sunton device

- README.md
- creations/oakdevtech.md
This is to reserve the Creator ID `0x4D69_XXXX` and add an initial entry, BREAD ESP32-S2 `0x4D69_0026`
> add oak dev tech

- README.md
- creations/makergo.md
This branch adds the "Maker Go" manufacturer, and the ESP32C3 Supermini that they manufacture as a new creation.
> added makergo supermini info

- README.md
- creations/spotpear.md
Ordered a couple Spotpear ESP32 LCD devices. Will work to bring them into the Circuit Python fold.
> Seantheitguy patch spotpear

- README.md
- creations/waveshare.md
Waveshare ESP32S3 device with no native USB.
> added waveshare device

- creations/sunton.md
added an ID for another Sunton CYD variant.
> added ID for Sunton ESP32-2432S032C

- README.md
- creations/dohome.md
Yet again, going down the rabbit hole of finding the original creators of aliexpress boards.
[CircuitPython PR](https://github.com/adafruit/circuitpython/pull/9300)
My editor cut a trailing space in the readme.
> NodeMcu-ESP32-C2

- README.md
- creations/april_brother.md
> Add April Brother and their AButton_V3 product

- creations/makergo.md
> Add MakerGo C6 SuperMini

- creations/waveshare.md
add ESP32-C6-Zero and ESP32-C6-LCD-1.47
Thanks.
> request Waveshare ESP32-C6 devives

- README.md
- creations/ddrown.md
needed for https://github.com/adafruit/circuitpython/pull/9883
> add community IDs for boards managed by ddrown

- creations/m5stack.md
I'm about to contribute a port of CircuitPython for this board.
> Add M5Stack Stick C Plus2

- creations/spotpear.md
Working on adding CircuitPython support for this esp32c3 w/ touchscreen device.
> added Spotpear 1.69 Touch ESP32C3 Device

- creations/elecrow.md
adding support for another Elecrow Crowpanel device.
> creationid for new elecrow device
